export const ROLES_TYPES = {
  USER: "USER",
  DOCTOR: "DOCTOR",
  SUB_ADMIN: "SUB_ADMIN",
  ADMIN: "ADMIN",
};

// export const DAYS_INDEX = [1,2,3,4,5,6,7]

export const TYPES = {
  EMAIL: "EMAIL",
  PASSWORD: "PASSWORD",
};

export const PERMISSION = {
  MANAGE_USERS_KEY: "MANAGE_USERS",
  CREATE_USER_KEY: "CREATE_USER",
  READ_USER_KEY: "READ_USER",
  UPDATE_USER_KEY: "UPDATE_USER",
  DELETE_USER_KEY: "DELETE_USER",

  //APPOINTMENTS
  MANAGE_APPOINTMENTS_KEY: "MANAGE_APPOINTMENTS", //ADMIN HAS ACCESS TO ALL CRUDS

  CREATE_APPOINTMENTS_KEY: "CREATE_APPOINTMENT", // USER AND DOCTOR CAN CREATE APPOINTMENTS
  READ_APPOINTMENTS_KEY: "READ_APPOINTMENT", // USER AND DOCTOR
  UPDATE_APPOINTMENT_KEY: "CREATE_APPOINTMENT", // USER AND DOCTOR WHO CREATED THE APPOINTMENT
  DELETE_APPOINTMENT_KEY: "DELETE_APPOINTMENT",
  CANCEL_APPOINTMENT_KEY: "CANCEL_APPOINTMENT", //USER AND DOCTOR
};
