export const TYPES = {
  EMAIL: "EMAIL",
  PASSWORD: "PASSWORD",
};

export const PERMISSION = {
  CREATE_USER_KEY: "CREATE_USER",
  READ_USER_KEY: "READ_USER",
  UPDATE_USER_KEY: "UPDATE_USER",
  DELETE_USER_KEY: "DELETE_USER",
};
